### PR TITLE
Hw4 dev

### PR DESCRIPTION
**Pull request by whhsu2**
hw4 commit

### CODE REVIEW

**Comment by bhavenp** [comment]
Problem 2: 25/25

**Comment by cridonoso** [comment]
**Problem 0:** _(total score: 10 )_ 
Working in branch HW4-dev
HW3 was merged
PR was generated


**Problem 4:** _(total score: 20)_ 
good job!

**Directory tree**: _(course policy)_ 
all is good


Doubts or comments before regrading -> OH thursday 18.30 - 19.30 
Regards,
Cristóbal

**Comment by cj-xin** [comment]
### Problem 3

 10/10: Great job!

**Comment by adityakaran** [comment]
**Problem 1:** 19.0 / 20
 - Nice job!

**Pull request merged**
