### PR TITLE
Hw6 dev

### PR DESCRIPTION
**Pull request by whhsu2**
hw6

### CODE REVIEW

**Comment by feiyu-chen96** [comment]
**Problem 3-C:** _(10/10)_ 
Good job!

**Comment by cridonoso** [comment]
**Problem 0:** _(total score: 10/10)_ 
Working in branch HW6-dev
HW5 was merged
PR was generated


**Problem 2:** _(total score: 30/30)_ 
good job!

**Directory tree**: _(course policy)_ 
all is good


Regards

**Comment by lindseysbrown** [comment]
3B: 10/10
Good job!

**Comment by adityakaran** [comment]
**Problem 1:** 10.0 / 10
 - Nice job

**Pull request merged**
